### ISSUE TITLE
[SUGGESTION] Imports

### ISSUE THREAD

**Issue by ProxyC0ding** [SahilGupta1331/space_Invaders#1]
Hey, Sahil!
I saw in your code that you made your imports weird. Let me explain:
You used this format in your code:
`import discord as discord`
If you're going to import Discord as Discord, just use `import discord`, it will work anyways.

Thanks!
~ Proxy

**Comment by SahilGupta1331** [comment]
Actually my vs-code intellisense was not working for python but when I used 'import as', it started working and then I just forgot to change it back...
Thanks for the suggestion! I fixed it up.
